dist: trusty
sudo: false
git:
  depth: 2
language: node_js
node_js:
- 6
- 8
- 9
before_script:
- test/scripts/ssh-setup.sh
script:
- eval $(cat ~/.ssh/agentrc) > /dev/null
- yarn test
after_script:
- test/scripts/ssh-teardown.sh
